### ISSUE TITLE
Support for opcodes for consensus incentives

### ISSUE THREAD

**Issue by uhudo** [algorandfoundation/puya#270]
## Problem

[Algorand 3.25.0](https://github.com/algorand/go-algorand/releases/tag/v3.25.0-stable) introduced [new AVM opcodes](https://github.com/algorand/go-algorand/pull/5984) related to consensus incentives.
For related smart contract applications, access to these opcodes is required.

## Solution

Expand [AcctParamsGet](https://algorandfoundation.github.io/puya/api-algopy.op.html#algopy.op.AcctParamsGet) and [Global ](https://algorandfoundation.github.io/puya/api-algopy.op.html#algopy.op.Global) classes with new corresponding methods.

**Comment by robdmoore** [comment]
Hi @uhudo we're just researching the status of those opcodes since they don't appear in the [latest langspec yet](https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/langspec_v10.json), which is what we use to generate the op code support.

**Comment by uhudo** [comment]
Hi @robdmoore, has there been any update on this? Or is there a workaround possible?
[Algorand 3.26.0](https://github.com/algorand/go-algorand/releases/tag/v3.26.0-stable) is now already live and I'd really need access to these new opcodes.

**Comment by robdmoore** [comment]
Good question! Let me follow up with the team.

**Comment by robdmoore** [comment]
Team are on it, should land within a few days
