### ISSUE TITLE
Wrong link for BigUInt code example on the Algopy Documentation

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/puya#289]
### Subject of the issue

https://algorandfoundation.github.io/puya/lg-types.html#biguint:~:text=200%20//%203-,Further%20examples%20available%20here.,-bool
This link goes to the uint64 code example not biguint. It should be directed to https://github.com/algorandfoundation/puya/blob/main/test_cases/stubs/biguint.py

### Expected behaviour
It should be directed to https://github.com/algorandfoundation/puya/blob/main/test_cases/stubs/biguint.py

### Actual behaviour
It goes to https://github.com/algorandfoundation/puya/blob/main/test_cases/stubs/uint64.py

**Comment by achidlow** [comment]
Thanks Chris, fix is live now
