### ISSUE TITLE
algokit compile python produces mysterious encoding warnings

### ISSUE THREAD

**Issue by rdowne** [algorandfoundation/puya#300]
### Subject of the issue

`algokit compile python` produces cryptic (and presumably incorrect) warnings, related to algosdk files being encoded as "utf-8 and not utf8"

Google/grep search yield nothing when searching for the offending package/source of the messages.

### Your environment

timestamp: 2024-08-22T19:01:05+00:00
AlgoKit: 2.2.3
AlgoKit Python: 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0] (location: /home/rdowne/.local/share/pipx/venvs/algokit)
OS: Linux-6.8.0-40-generic-x86_64-with-glibc2.39
docker: 24.0.7
docker compose: 2.24.6+ds1-0ubuntu2
git: 2.43.0
python: 3.12.3 (location: /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/bin/python)
python3: 3.12.3 (location: /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/bin/python3)
pipx: 1.4.3
poetry: 1.8.3
node: 22.6.0
npm: 10.8.2

### Steps to reproduce

1. Run algokit compile python on a smart contract: `algokit compile python ./v1_1/stake_purepy_contract.py --out-dir ./v1_1/artifacts/ --output-arc32`

### Expected behaviour
algokit will compile the smart contract

### Actual behaviour
algokit vents page full of, e.g.

> /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/lib/python3.12/site-packages/algosdk/v2client/models/account_participation.py:1 warning: UH OH SPAGHETTI-O's, darn tootin' non-utf8(?!) encoded file encountered: /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/lib/python3.12/site-packages/algosdk/v2client/models/account_participation.py encoded as utf-8
> /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/lib/python3.12/site-packages/algosdk/v2client/models/account.py:1 warning: UH OH SPAGHETTI-O's, darn tootin' non-utf8(?!) encoded file encountered: /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/lib/python3.12/site-packages/algosdk/v2client/models/account.py encoded as utf-8
> /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/lib/python3.12/site-packages/algosdk/v2client/models/__init__.py:1 warning: UH OH SPAGHETTI-O's, darn tootin' non-utf8(?!) encoded file encountered: /home/rdowne/Nimblr/nimble-smart-contracts-dev/venv2/lib/python3.12/site-packages/algosdk/v2client/models/__init__.py encoded as utf-8

**Comment by aorumbayev** [comment]
@daniel-makerx any chance you can take a look?

**Comment by daniel-makerx** [comment]
Thanks @rdowne for logging the issue and the PR to address it, unfortunately your fix failed the automated tests, possibly due to differences in platforms. Have merged #302 which address this issue by using the python `codec` module to find the appropriate coded for the discovered encoding and checking it's name, this should handle the various utf8 aliases present.

Please feel free to reopen the issue if this fix doesn't address the issue
